# Generated by Django 6.0 on 2026-01-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
